### ISSUE TITLE
getting alot of errors when starting the bot

### ISSUE THREAD

**Issue by pokzy** [Alan4747/instagram-auto-create-account#40]
can't start the code, always getting error: one of the arguments --firefox --chrome is required

**Comment by pokzy** [comment]
> can't start the code, always getting error: one of the arguments --firefox --chrome is required

i fixed this, but i have another problem. when i start the botaccountcreate.py i get this errors:
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\pythonProject1\botAccountCreate.py", line 18, in <module>
    args = parser.parse_args()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\argparse.py", line 1818, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\argparse.py", line 1851, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\argparse.py", line 2104, in _parse_known_args
    self.error(msg % ' '.join(names))
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\argparse.py", line 2573, in error
    self.print_usage(_sys.stderr)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\argparse.py", line 2543, in print_usage
    self._print_message(self.format_usage(), file)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\argparse.py", line 2509, in format_usage
    return formatter.format_help()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\argparse.py", line 283, in format_help
    help = self._root_section.format_help()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\argparse.py", line 321, in _format_usage
    action_usage = format(optionals + positionals, groups)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\argparse.py", line 396, in _format_actions_usage
    start = actions.index(group._group_actions[0])
IndexError: list index out of range

Process finished with exit code 1

**Comment by pokzy** [comment]
fixed it.

**Comment by mamorutakamura** [comment]
how did u run the program? what did u type

**Comment by mamorutakamura** [comment]
How did you fix it?? i am getting the same error.

**Comment by pokzy** [comment]
> How did you fix it?? i am getting the same error.

check pull request
