### ISSUE TITLE
name error

### ISSUE THREAD

**Issue by mhdashik00** [Alan4747/instagram-auto-create-account#53]
Traceback (most recent call last):
  File "/home/kali/instagram-auto-create-account/botAccountCreate.py", line 13, in <module>
    args = parser.parse_args()
NameError: name 'parser' is not defined

**Comment by msr8** [comment]
Same error,
```
File "/Users/[user]/instagram-auto-create-account/botAccountCreate.py", line 13, in <module>
    args = parser.parse_args()
NameError: name 'parser' is not defined
```

Python Version: Python 3.9.6
Operating System: MacOS Catalina 10.15.2

**Comment by msr8** [comment]
Fixed it using https://github.com/Alan4747/instagram-auto-create-account/issues/52

**Comment by AbolfazlGolestani** [comment]
Open the file and add this code in line 12
parser = argparse.ArgumentParser()
