### ISSUE TITLE
Error.What should I do? I confused!

### ISSUE THREAD

**Issue by AbolfazlGolestani** [Alan4747/instagram-auto-create-account#54]
Traceback (most recent call last):
  File "C:\Users\Abolfazl\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Abolfazl\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Abolfazl\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Abolfazl\Downloads\instagram-auto-create-account-master\instagram-auto-create-account-master\botAccountCreate.py", line 20, in <module>
    driver = webdriver.Chrome(r'C:\Users\Abolfazl\Downloads\instagram-auto-create-account-master\instagram-auto-create-account-master')
  File "C:\Users\Abolfazl\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Abolfazl\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'instagram-auto-create-account-master' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by AbolfazlGolestani** [comment]
$ python botAccountCreate.py
Mozilla/5.0 (Windows NT 4.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36
['cmed_al@texasaol.com']
Anubhav Hammoud
florence.ted
Traceback (most recent call last):
  File "C:\Users\Abolfazl\Downloads\instagram-auto-create-account-master\instagram-auto-create-account-master\botAccountCreate.py", line 64, in <module>
    driver.find_element_by_xpath("//*[@id='react-root']/section/main/div/div/div[1]/div/div[4]/div/div/span/span[1]/select").click()
  File "C:\Users\Abolfazl\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Abolfazl\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Abolfazl\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Abolfazl\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='react-root']/section/main/div/div/div[1]/div/div[4]/div/div/span/span[1]/select"}
  (Session info: chrome=95.0.4638.69)

**Comment by crocogab** [comment]
the bot didnt manage basic error
u need to patch it 
its not that hard but can be long

**Comment by AbolfazlGolestani** [comment]
How?

**Comment by pokzy** [comment]
`Message: no such element: Unable to locate element: {"method":"xpath","selector":"//[@id='react-root']/section/main/div/div/div[1]/div/div[4]/div/div/span/span[1]/select"}`

it means xpath has changed.

**Comment by pokzy** [comment]
`selenium.common.exceptions.WebDriverException: Message: 'instagram-auto-create-account-master' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

wrong path to chromedriver

**Comment by crocogab** [comment]
It is not only xpath. After you patched this it doesnt work anymore because insta detect it and block account creation. I tried.
