### ISSUE TITLE
I have no idea what's happening

### ISSUE THREAD

**Issue by biraj4uu** [Alan4747/instagram-auto-create-account#61]
i got this error code. can you please anyone tell me what needs to be done? how do i fix this issue?

C:\Users\BIraj\PycharmProjects\pythonProject2\venv\Scripts\python.exe C:/Users/BIraj/PycharmProjects/pythonProject2/botAccountCreate.py
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.15 (KHTML, like Gecko) Chrome/24.0.1295.0 Safari/537.15
Traceback (most recent call last):
  File "C:\Users\BIraj\PycharmProjects\pythonProject2\venv\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\BIraj\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\BIraj\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\BIraj\PycharmProjects\pythonProject2\botAccountCreate.py", line 20, in <module>
    driver= webdriver.Chrome(options=options, executable_path=r"your chrome driver path here")
  File "C:\Users\BIraj\PycharmProjects\pythonProject2\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\BIraj\PycharmProjects\pythonProject2\venv\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'your chrome driver path here' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Process finished with exit code 1

**Comment by priyaank2004** [comment]
> in line 20 of the file botAccountCreate.py you have to specify where the chrome driver is saved

did this program work for u? do u receive insta verfication code on email-fake?
